# Generated by Django 5.1.6 on 2025-03-27 01:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Marzo 2025', 'Marzo 2025'), ('Abril 2025', 'Abril 2025'), ('Mayo 2025', 'Mayo 2025'), ('Junio 2025', 'Junio 2025'), ('Julio 2025', 'Julio 2025'), ('Agosto 2025', 'Agosto 2025'), ('Septiembre 2025', 'Septiembre 2025'), ('Octubre 2025', 'Octubre 2025'), ('Noviembre 2025', 'Noviembre 2025'), ('Diciembre 2025', 'Diciembre 2025'), ('Enero 2026', 'Enero 2026'), ('Febrero 2026', 'Febrero 2026')], max_length=20, unique=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Meses',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='calendario.mes')),
            ],
            options={
                'verbose_name_plural': 'Fotos del Mes',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='CancionMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('archivo_mp3', models.FileField(blank=True, null=True, upload_to='canciones/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('enlace_externo', models.URLField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='calendario.mes')),
            ],
            options={
                'verbose_name_plural': 'Canciones del Mes',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
